# ---------------------------------------------------------------------------
# Author: Labiyb M. Said — DevSecOps Engineer
# Contact: saidlabiybm@gmail.com
# ---------------------------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-dashboard
  labels:
    app.kubernetes.io/part-of: audit-collector
